# 建议使用yml 结构清晰
# Yet  Another Markup Language
server:
  port: 8080                  # 此处设置的服务的访问端口配置
#  servlet:
#    context-path: /liuawen

spring:
  messages:                 # 定义资源文件，多个资源文件使用“,”分割
    basename: i18n/Messages
---
spring:
  profiles:
    active: dev             # 定义默认生效的环境
---
spring:
  profiles: dev
server:
  port: 7070                # 此处设置的服务的访问端口配置
---
spring:
  profiles: beta
server:
  port: 8080                # 此处设置的服务的访问端口配置
---
spring:
  profiles: product
server:
  port: 80                  # 此处设置的服务的访问端口配置